### ISSUE TITLE
Error: "cannot convert the series to  <class 'float'>"

### ISSUE THREAD

**Issue by jbryantvt** [PlantSynBioLab/opentrons#1]
When I simulate my opentrons script, I am trying to call a value from a dataframe. I keep getting the error "cannot convert the series to  <class 'float'>"

The error is on line 39 where I call df['water to add']

I thought that I could easily resolve it by converting this column of the dataframe to floating numbers but I can't get it to work

**Comment by jbryantvt** [comment]
@wrightrc

**Comment by wrightrc** [comment]
Hmm, seems like it is an issue in conversions in dataframes. Looks like `.applymap(float)` is the way to convert columns to floats in a dataframe from:
https://stackoverflow.com/questions/41000428/python-typeerror-cannot-convert-the-series-to-class-int-when-trying-to-do-m/41002511

**Comment by jbryantvt** [comment]
So for this line of code:
left_pipette.aspirate(volume = df['water to add'], location = watertuberack['A1'], rate=2.0)

I'm getting this error:
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

It doesn't seem to like calling object from dataframes. I've tried some things but can't seem to get it to work

**Comment by jbryantvt** [comment]
figured it out.
to call an object from a dataframe:
df.loc[row].at[column]
